################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

mode: old

#==============================================================================
# Common
#==============================================================================

# The external address of the host on which the JobManager runs and can be
# reached by the TaskManagers and any clients which want to connect. This setting
# is only used in Standalone mode and may be overwritten on the JobManager side
# by specifying the --host <hostname> parameter of the bin/jobmanager.sh executable.
# In high availability mode, if you use the bin/start-cluster.sh script and setup
# the conf/masters file, this will be taken care of automatically. Yarn/Mesos
# automatically configure the host name based on the hostname of the node where the
# JobManager runs.

jobmanager.rpc.address: cloud-11

# The RPC port where the JobManager is reachable.

jobmanager.rpc.port: 6123


# The heap size for the JobManager JVM

jobmanager.heap.mb: 8192


# The heap size for the TaskManager JVM

#taskmanager.heap.mb: 28672
taskmanager.heap.mb: 23552

# The number of task slots that each TaskManager offers. Each slot runs one parallel pipeline.

taskmanager.numberOfTaskSlots: 1

# The parallelism used for programs that did not specify and other parallelism.

parallelism.default: 1

# The default file system scheme and authority.
# 
# By default file paths without scheme are interpreted relative to the local
# root file system 'file:///'. Use this to override the default and interpret
# relative paths relative to a different file system,
# for example 'hdfs://mynamenode:12345'
#
# fs.default-scheme

#==============================================================================
# High Availability
#==============================================================================

# The high-availability mode. Possible options are 'NONE' or 'zookeeper'.
#
# high-availability: zookeeper

# The path where metadata for master recovery is persisted. While ZooKeeper stores
# the small ground truth for checkpoint and leader election, this location stores
# the larger objects, like persisted dataflow graphs.
# 
# Must be a durable file system that is accessible from all nodes
# (like HDFS, S3, Ceph, nfs, ...) 
#
# high-availability.storageDir: hdfs:///flink/ha/

# The list of ZooKeeper quorum peers that coordinate the high-availability
# setup. This must be a list of the form:
# "host1:clientPort,host2:clientPort,..." (default clientPort: 2181)
#
# high-availability.zookeeper.quorum: localhost:2181


# ACL options are based on https://zookeeper.apache.org/doc/r3.1.2/zookeeperProgrammers.html#sc_BuiltinACLSchemes
# It can be either "creator" (ZOO_CREATE_ALL_ACL) or "open" (ZOO_OPEN_ACL_UNSAFE)
# The default value is "open" and it can be changed to "creator" if ZK security is enabled
#
# high-availability.zookeeper.client.acl: open

#==============================================================================
# Fault tolerance and checkpointing
#==============================================================================

# The backend that will be used to store operator state checkpoints if
# checkpointing is enabled.
#
# Supported backends are 'jobmanager', 'filesystem', 'rocksdb', or the
# <class-name-of-factory>.
#
# state.backend: filesystem

# Directory for checkpoints filesystem, when using any of the default bundled
# state backends.
#
# state.checkpoints.dir: hdfs://namenode-host:port/flink-checkpoints

# Default target directory for savepoints, optional.
#
# state.savepoints.dir: hdfs://namenode-host:port/flink-checkpoints

# Flag to enable/disable incremental checkpoints for backends that
# support incremental checkpoints (like the RocksDB state backend). 
#
# state.backend.incremental: false

#==============================================================================
# Web Frontend
#==============================================================================

# The address under which the web-based runtime monitor listens.
#
jobmanager.web.address: cloud-11

# The port under which the web-based runtime monitor listens.
# A value of -1 deactivates the web server.

rest.port: 8081

# Flag to specify whether job submission is enabled from the web-based
# runtime monitor. Uncomment to disable.

#jobmanager.web.submit.enable: false

#==============================================================================
# Advanced
#==============================================================================

# Override the directories for temporary files. If not specified, the
# system-specific Java temporary directory (java.io.tmpdir property) is taken.
#
# For framework setups on Yarn or Mesos, Flink will automatically pick up the
# containers' temp directories without any need for configuration.
#
# Add a delimited list for multiple directories, using the system directory
# delimiter (colon ':' on unix) or a comma, e.g.:
#     /data1/tmp:/data2/tmp:/data3/tmp
#
# Note: Each directory entry is read from and written to by a different I/O
# thread. You can include the same directory multiple times in order to create
# multiple I/O threads against that directory. This is for example relevant for
# high-throughput RAIDs.
#
# io.tmp.dirs: /tmp

# Specify whether TaskManager's managed memory should be allocated when starting
# up (true) or when memory is requested.
#
# We recommend to set this value to 'true' only in setups for pure batch
# processing (DataSet API). Streaming setups currently do not use the TaskManager's
# managed memory: The 'rocksdb' state backend uses RocksDB's own memory management,
# while the 'memory' and 'filesystem' backends explicitly keep data as objects
# to save on serialization cost.
#
# taskmanager.memory.preallocate: false

# The classloading resolve order. Possible values are 'child-first' (Flink's default)
# and 'parent-first' (Java's default).
#
# Child first classloading allows users to use different dependency/library
# versions in their application than those in the classpath. Switching back
# to 'parent-first' may help with debugging dependency issues.
#
# classloader.resolve-order: child-first

# The amount of memory going to the network stack. These numbers usually need 
# no tuning. Adjusting them may be necessary in case of an "Insufficient number
# of network buffers" error. The default min is 64MB, teh default max is 1GB.
# 
# taskmanager.network.memory.fraction: 0.1
# taskmanager.network.memory.min: 67108864
# taskmanager.network.memory.max: 1073741824

#==============================================================================
# Flink Cluster Security Configuration
#==============================================================================

# Kerberos authentication for various components - Hadoop, ZooKeeper, and connectors -
# may be enabled in four steps:
# 1. configure the local krb5.conf file
# 2. provide Kerberos credentials (either a keytab or a ticket cache w/ kinit)
# 3. make the credentials available to various JAAS login contexts
# 4. configure the connector to use JAAS/SASL

# The below configure how Kerberos credentials are provided. A keytab will be used instead of
# a ticket cache if the keytab path and principal are set.

# security.kerberos.login.use-ticket-cache: true
# security.kerberos.login.keytab: /path/to/kerberos/keytab
# security.kerberos.login.principal: flink-user

# The configuration below defines which JAAS login contexts

# security.kerberos.login.contexts: Client,KafkaClient

#==============================================================================
# ZK Security Configuration
#==============================================================================

# Below configurations are applicable if ZK ensemble is configured for security

# Override below configuration to provide custom ZK service name if configured
# zookeeper.sasl.service-name: zookeeper

# The configuration below must match one of the values set in "security.kerberos.login.contexts"
# zookeeper.sasl.login-context-name: Client

#==============================================================================
# HistoryServer
#==============================================================================

# The HistoryServer is started and stopped via bin/historyserver.sh (start|stop)

# Directory to upload completed jobs to. Add this directory to the list of
# monitored directories of the HistoryServer as well (see below).
#jobmanager.archive.fs.dir: hdfs:///completed-jobs/

# The address under which the web-based HistoryServer listens.
#historyserver.web.address: 0.0.0.0

# The port under which the web-based HistoryServer listens.
#historyserver.web.port: 8082

# Comma separated list of directories to monitor for completed jobs.
#historyserver.archive.fs.dir: hdfs:///completed-jobs/

# Interval in milliseconds for refreshing the monitored directories.
#historyserver.archive.fs.refresh-interval: 10000


state.backend: custom
taskmanager.network.netty.replication.port: 6130
taskmanager.network.netty.replication.server.numThreads: 8
taskmanager.network.netty.replication.client.numThreads: 8
taskmanager.network.netty.replication.arenas: 8
taskmanager.network.replica.memory.max: 5368709120
taskmanager.network.replica.memory.fraction: 0.3
taskmanager.checkpoint.reader: zero-copy-fadvise-lazy
state.replication.factor: 1 
taskmanager.network.netty.transport: epoll
taskmanager.network.memory.fraction: 0.3
taskmanager.network.memory.min: 536870912
taskmanager.network.memory.max: 8589934592
taskmanager.memory.fraction: 0.5
taskmanager.rpc.port: 6132
taskmanager.data.port: 6131
taskmanager.tmp.dirs: /data/1/peel/flink/tmp:/data/2/peel/flink/tmp:/data/4/peel/flink/tmp:/data/3/peel/flink/tmp
#state.backend.rocksdb.localdir: /data/2/peel/flink/tmp,/data/4/peel/flink/tmp,/data/1/peel/flink/tmp,/data/3/peel/flink/tmp
state.backend.rocksdb.localdir: /data/1/peel/flink/tmp,/data/3/peel/flink/tmp
#state.checkpoints.dir: /data/1/peel/flink/tmp:/data/3/peel/flink/tmp:/data/4/peel/flink/tmp:/data/2/peel/flink/tmp
#state.replication.fs.dir: /data/3/peel/flink/tmp:/data/1/peel/flink/tmp:/data/4/peel/flink/tmp:/data/2/peel/flink/tmp
state.replication.fs.dir: /data/4/peel/flink/tmp:/data/2/peel/flink/tmp
state.checkpoints.dir: /data/4/peel/flink/tmp:/data/2/peel/flink/tmp
state.replication.replica-slots: 120
taskmanager.network.memory.buffers-per-channel: 4
taskmanager.network.memory.buffers-per-replica: 255
taskmanager.network.memory.buffers-per-replica-max: 256
taskmanager.state.rocksdb.predef: spinning-memory
taskmanager.network.memory.floating-buffers-per-gate: 64
state.replication.jm.fs.dir: /share/hadoop/danish/flink-experiments/vault/
taskmanager.network.memory.buffers-replica-size: 32768
state.replication.dumpStats: true
taskmanager.network.netty.replication.low-watermark.factor: 1
taskmanager.network.netty.replication.high-watermark.factor: 2
state.replication.num-connections-pool: 1
state.replication.writer-threads: 8
taskmanager.network.netty.replication.write-spin-count: 8
taskmanager.network.netty.replication.readahead.threshold: 4194304
taskmanager.state.rocksdb.logging.enabled: false
akka.ask.timeout: 20 s
state.replication.ack.timeout: 23600000
#state.replication.ack.timeout: 180000
akka.watch.heartbeat.interval: 20 s
akka.watch.threshold: 13
#taskmanager.network.netty.replication.share-pools: true
#taskmanager.network.netty.replication.server-write-limit: 12582912
#taskmanager.network.detailed-metrics: true
state.replication.placement.bin-packing-cache: 4
jobmanager.execution.failover-strategy: handover
restart-strategy: handover
#state.backend.rocksdb.metrics.compaction-pending: true
#state.backend.rocksdb.metrics.num-immutable-mem-table: true
#state.backend.rocksdb.metrics.mem-table-flush-pending: true
#state.backend.rocksdb.metrics.cur-size-active-mem-table: true
#state.backend.rocksdb.cur-size-all-mem-tables: true
#state.backend.rocksdb.total-sst-files-size: true
#state.backend.rocksdb.num-running-compactions: true
#state.backend.rocksdb.actual-delayed-write-rate: true
#env.java.opts: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=31337  -XX:+AggressiveOpts -XX:+TieredCompilation -server -XX:CompileThreshold=200 -XX:+UseG1GC

#env.java.opts: -Dorg.apache.flink.shaded.netty4.io.netty.leakDetectionLevel=paranoid -XX:+AggressiveOpts -XX:+TieredCompilation -server -XX:CompileThreshold=200 -XX:+UseG1GC

#env.java.opts: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=31337 -server -XX:+UseG1GC -XX:MetaspaceSize=128m -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80

env.java.opts: -XX:+UseNUMA  -XX:+UseCompressedOops -XX:+TieredCompilation -server -XX:+UseG1GC -Dorg.apache.flink.shaded.netty4.io.netty.buffer.bytebuf.checkAccessible=false -Dorg.apache.flink.shaded.netty4.io.netty.leakDetection.level=DISABLED -Dorg.apache.flink.shaded.netty4.io.netty.allocator.tinyCacheSize=4096 -Dorg.apache.flink.shaded.netty4.io.netty.allocator.normalCacheSize=1024 
#env.java.opts: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=31337 -XX:+UseCompressedOops -XX:+TieredCompilation -server -XX:+UseG1GC -Dorg.apache.flink.shaded.netty4.io.netty.buffer.bytebuf.checkAccessible=false -Dorg.apache.flink.shaded.netty4.io.netty.leakDetection.level=DISABLED -Dorg.apache.flink.shaded.netty4.io.netty.allocator.tinyCacheSize=4096 -Dorg.apache.flink.shaded.netty4.io.netty.allocator.normalCacheSize=1024 
#metrics.reporters: slf4j
#metrics.reporter.slf4j.class: org.apache.flink.metrics.slf4j.Slf4jReporter
#metrics.reporter.slf4j.interval: 10 SECONDS


#metrics.reporter.gang.class: org.apache.flink.metrics.ganglia.GangliaReporter
#metrics.reporter.gang.host: cloud-11.dima.tu-berlin.de
#metrics.reporter.gang.port: 8649
#metrics.reporter.gang.ttl: 1
#metrics.reporter.gang.addressingMode: MULTICAST


rhino.actions.log: /share/hadoop/danish/flink-experiments/test-data/morpheus-tests/policy-rates-repo/rhino/rhino-actions.log

metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
metrics.reporter.prom.port: 9250

morpheus.policies.rescaling.enabled: false
morpheus.policies.load-balancing.enabled: true
morpheus.policies.load-balancing.warmup-cycles: 12
morpheus.policies.load-balancing.agg-cycles: 5

web.upload.dir: /share/hadoop/danish/flink-experiments/test-data/jars/