rhino.actions.log: /home/danish/FastWorkspace/BDMA/TUB/incremental-migration/morpheus-tests/rhino-logs/rhino-actions.log

metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
metrics.reporter.prom.port: 9250

morpheus.policies.load-balancing.warmup-cycles: 12
morpheus.policies.load-balancing.agg-cycles: 5
