{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic=\"words\"}[30s]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic=\"words\"}[30s]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic=\"words\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic=\"words\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic=\"words\"}[30s]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages Out Per Topic (FLINK Consumption rate)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_job_task_numRecordsOut{task_name=\"Source:_Custom_Source____Splitter_FlatMap\"}[10s]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Event Time Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_eventLatency",
     "legendFormat": "{{subtask_index}}"
    }
   ]
  },
  {
   "title": "Event Time Latency (manual)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_eventLatencyDur/flink_taskmanager_job_task_operator_eventLatencyCount",
     "legendFormat": "{{subtask_index}}"
    }
   ]
  },
  {
   "title": "ObservedProcessing rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_observedProcRate",
     "legendFormat": "{{subtask_index}}"
    },
    {}
   ]
  },
  {
   "title": "True Processing rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_trueProcRate",
     "legendFormat": "{{subtask_index}}"
    },
    {}
   ]
  },
  {
   "title": "waistedTime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_waistedTime",
     "legendFormat": "{{subtask_index}}"
    },
    {}
   ]
  },
  {
   "title": "Event Time latency  vs Processin time ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_eventLatency - flink_taskmanager_job_task_operator_procLatency",
     "legendFormat": "{{subtask_index}}"
    },
    {}
   ]
  },
  {
   "title": "Average size of object",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Average Size" }
   ],
   "targets": [
    {
     "expr": "((sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic!=\"\"}[30s])))/(sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic!=\"\"}[30s]))))",
     "legendFormat": "size of object in {{topic}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"kafka\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Use",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"java\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}